"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class rotation_t(object):
    __slots__ = ["yaw", "pitch", "roll"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.yaw = 0.0
        self.pitch = 0.0
        self.roll = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(rotation_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fff", self.yaw, self.pitch, self.roll))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rotation_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rotation_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = rotation_t()
        self.yaw, self.pitch, self.roll = struct.unpack(">fff", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if rotation_t in parents: return 0
        tmphash = (0xaeab9f50dbfa494) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if rotation_t._packed_fingerprint is None:
            rotation_t._packed_fingerprint = struct.pack(">Q", rotation_t._get_hash_recursive([]))
        return rotation_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

