"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from rotation_t import rotation_t

from location_t import location_t

class transformation_t(object):
    __slots__ = ["id", "location", "rotation"]

    IS_LITTLE_ENDIAN = False;
    def __init__(self):
        self.id = 0
        self.location = location_t()
        self.rotation = rotation_t()

    def encode(self):
        buf = BytesIO()
        buf.write(transformation_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.id))
        assert self.location._get_packed_fingerprint() == location_t._get_packed_fingerprint()
        self.location._encode_one(buf)
        assert self.rotation._get_packed_fingerprint() == rotation_t._get_packed_fingerprint()
        self.rotation._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != transformation_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return transformation_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = transformation_t()
        self.id = struct.unpack(">i", buf.read(4))[0]
        self.location = location_t._decode_one(buf)
        self.rotation = rotation_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if transformation_t in parents: return 0
        newparents = parents + [transformation_t]
        tmphash = (0xa9383d63c14aeb45+ location_t._get_hash_recursive(newparents)+ rotation_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if transformation_t._packed_fingerprint is None:
            transformation_t._packed_fingerprint = struct.pack(">Q", transformation_t._get_hash_recursive([]))
        return transformation_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

